#pragma once

#define DEFAULT_SERVER_ADDR "127.0.0.1"
#define DEFAULT_SERVER_PORT 30000

#define BUF_SIZE 1024
#define USERNAME_LEN 32

#define REDIS_UNLIMITED_CAPACITY 0
#define REDIS_MAX_CAPACITY 20
